exports.PRODUCT_SIZE = [
  "10cl",
  "25cl",
  "30cl",
  "33cl",
  "50cl",
  "60cl",
  "65cl",
  "70cl",
  "75cl",
  "80cl",
  "85cl",
  "90cl",
  "95cl",
  "100cl",
  "125cl",
  "150cl",
  "200cl",
  "250cl",
  "10g",
  "20g",
  "30g",
  "50g",
  "100g",
  "200g",
  "500g",
];

// pays de l'afrique de l'ouest

exports.PAYS = [
  {
    code: "benin",
    nom: "Bénin",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg",
    cities: [
      "Cotonou",
      "Porto-Novo",
      "Parakou",
      "Djougou",
      "Bohicon",
      "Kandi",
      "Lokossa",
      "Abomey-Calavi",
      "Natitingou",
      "Save",
      "Ouidah",
      "Malanville",
      "Cové",
      "Tanguiéta",
      "Pobè",
      "Savalou",
      "Sakété",
      "Bassila",
      "Dassa-Zoumè",
      "Tchaourou",
      "Dogbo-Tota",
      "Aplahoué",
      "Allada",
      "Sèmè-Kpodji",
      "Tchaourou",
      "Nikki",
      "Bembèrèkè",
      "Beterou",
      "Grand-Popo",
      "Djougou",
      "Kétou",
      "Athiémé",
    ],
  },
  {
    code: "burkina_faso",
    nom: "Burkina Faso",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg",
    cities: [
      "Ouagadougou",
      "Bobo-Dioulasso",
      "Koudougou",
      "Banfora",
      "Dédougou",
      "Ouahigouya",
      "Fada N'Gourma",
      "Tenkodogo",
      "Kaya",
      "Houndé",
      "Dori",
      "Réo",
      "Manga",
      "Ziniaré",
      "Garango",
      "Koupéla",
      "Kombissiri",
      "Yako",
      "Ouargaye",
      "Diapaga",
      "Nouna",
      "Gourcy",
      "Leo",
      "Solenzo",
      "Koudougou",
      "Pô",
      "Dano",
      "Tougan",
      "Boulsa",
      "Gourcy",
      "Kombissiri",
      "Koupéla",
      "Léo",
      "Nouna",
      "Réo",
      "Tenkodogo",
    ],
  },
  {
    code: "cap_vert",
    nom: "Cap-Vert",
    devise: "CVE",
    flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg",
    cities: [
      "Praia",
      "Mindelo",
      "Santa Maria",
      "Cova Figueira",
      "Tarrafal",
      "Assomada",
      "Pedra Badejo",
      "Porto Novo",
      "Vila do Maio",
      "Espargos",
      "Vila da Ribeira Brava",
      "Cidade Velha",
      "Calheta de São Miguel",
      "Ponta do Sol",
      "São Filipe",
      "Cidade Baixa",
      "Sal Rei",
      "São Domingos",
      "Cachoeira",
      "São Miguel",
      "Picos",
      "João Teves",
      "São Lourenço dos Órgãos",
      "Tarrafal de São Nicolau",
      "Mosteiros",
      "Ribeira Grande",
      "Porto Novo",
      "Lomba",
      "Ribeira Brava",
      "Tarrafal",
      "Paul",
      "Porto Ingles",
    ],
  },
  {
    code: "cote_d_ivoire",
    nom: "Côte d'Ivoire",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg",
    cities: [
      "Abidjan",
      "Yamoussoukro",
      "Bouaké",
      "Daloa",
      "San-Pédro",
      "Korhogo",
      "Man",
      "Divo",
      "Gagnoa",
      "Anyama",
      "Abobo",
      "Séguéla",
      "Oumé",
      "Tiassalé",
      "Dabou",
      "Toumodi",
      "Bondoukou",
      "Guiglo",
      "Bongouanou",
      "Issia",
      "Sassandra",
      "Bangolo",
      "Akoupé",
      "Zuénoula",
      "Grand-Bassam",
      "Abengourou",
      "Agnibilékrou",
      "Dimbokro",
      "Adzopé",
      "Aboisso",
      "Katiola",
      "Tengrela",
      "Duékoué",
      "Ferkessedougou",
      "Lakota",
      "Sinfra",
      "Vavoua",
      "Touba",
      "Kouto",
      "Bouna",
      "Séguélon",
      "Tanda",
      "Agboville",
      "Tabou",
      "Guibéroua",
      "Odienné",
      "Boundiali",
      "Daoukro",
      "Biankouma",
      "Zuénoula",
      "Odienné",
      "Yamoussoukro",
      "Abidjan",
    ],
  },
  {
    code: "gambie",
    nom: "Gambie",
    devise: "GMD",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg",
    cities: [
      "Banjul",
      "Serekunda",
      "Brikama",
      "Bakau",
      "Farafenni",
      "Lamin",
      "Kanifing",
      "Kololi",
      "Basse Santa Su",
      "Bakoteh",
      "Bansang",
      "Barra",
      "Brufut",
      "Essau",
      "Gunjur",
      "Kuntaur",
      "Manjai",
      "Sabieh",
      "Sukuta",
      "Tanji",
      "Farafenni",
      "Janjanbureh",
      "Kerewan",
      "Kudang",
      "Kwinella",
      "Newtown",
      "Old Jeshwang",
      "Old Yundum",
      "Saba",
      "Serekunda",
      "Soma",
      "Sotuma Sere",
      "Wassu",
      "Yundum",
      "Sukuta",
      "Kotu",
      "Jambur",
      "Kanifing",
      "Serekunda",
      "Bakoteh",
      "Kololi",
    ],
  },
  {
    code: "ghana",
    nom: "Ghana",
    devise: "GHS",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
    cities: [
      "Accra",
      "Kumasi",
      "Tamale",
      "Takoradi",
      "Sekondi-Takoradi",
      "Cape Coast",
      "Sunyani",
      "Ho",
      "Bolgatanga",
      "Wa",
      "Techiman",
      "Koforidua",
      "Nungua",
      "Tema",
      "Ashiaman",
      "Dome",
      "Wa",
      "Teshie",
      "Sekondi",
      "Obuasi",
      "Madina",
      "Kintampo",
      "Adenta",
      "Nsawam",
      "Hohoe",
      "Akim Oda",
      "Tarkwa",
      "Akropong",
      "Bawku",
      "Navrongo",
      "Keta",
      "Berekum",
      "Swedru",
      "Nkawkaw",
      "Dunkwa-on-Offin",
      "Axim",
      "Kibi",
      "Shama Junction",
      "Mampong",
      "Anloga",
      "Bogoso",
      "Aburi",
      "Apam",
      "Suhum",
      "Elmina",
      "Salaga",
      "Bibiani",
    ],
  },
  {
    code: "guinee",
    nom: "Guinée",
    devise: "GNF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg",
    cities: [
      "Conakry",
      "Nzérékoré",
      "Kankan",
      "Kindia",
      "Labé",
      "Boffa",
      "Macenta",
      "Kissidougou",
      "Gueckedou",
      "Coyah",
      "Kamsar",
      "Fria",
      "Siguiri",
      "Pita",
      "Dabola",
      "Mamou",
      "Télimélé",
      "Kouroussa",
      "Boké",
      "Faranah",
      "Tougué",
      "Dubréka",
      "Kankan",
      "Dinguiraye",
      "Forécariah",
      "Koubia",
      "Mandiana",
      "Dalaba",
      "Guékédou",
      "Kérouané",
      "Yomou",
      "Gaoual",
      "Lélouma",
      "Tougué",
      "Koundara",
      "Kissidougou",
      "Télimélé",
      "Siguiri",
      "Mali",
      "Coyah",
      "Dabola",
      "Koubia",
      "Kérouané",
      "Mandiana",
      "Faranah",
      "Beyla",
      "Télimélé",
      "Forécariah",
      "Mamou",
      "Dalaba",
      "Dinguiraye",
      "Gaoual",
      "Koundara",
      "Fria",
      "Boké",
      "Macenta",
    ],
  },
  {
    code: "guinee_bissau",
    nom: "Guinée-Bissau",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg",
    cities: [
      "Bissau",
      "Bafatá",
      "Gabú",
      "Bolama",
      "Cacheu",
      "Canchungo",
      "Buba",
      "Mansôa",
      "Quinhamel",
      "Bissorã",
      "Farim",
      "Fulacunda",
      "Catió",
      "Quebo",
      "Cacine",
      "Bolama",
      "Bissau",
      "Bubaque",
      "Canchungo",
      "Bolama",
      "Bafatá",
      "Gabú",
      "Mansôa",
      "Cacheu",
      "Catió",
      "Farim",
      "Bissorã",
      "Buba",
      "Quebo",
      "Fulacunda",
      "Bubaque",
      "Bissau",
    ],
  },
  {
    code: "liberia",
    nom: "Libéria",
    devise: "LRD",
    flag: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg",
    cities: [
      "Monrovia",
      "Gbarnga",
      "Bensonville",
      "Harper",
      "Zwedru",
      "Buchanan",
      "Ganta",
      "Kakata",
      "Voinjama",
      "Barclayville",
      "Sanniquellie",
      "Bopolu",
      "Buchanan",
      "Zorzor",
      "Kasongo",
      "Pleebo",
      "Voinjama",
      "Fish Town",
      "Gbarnga",
      "Ganta",
      "Sanniquellie",
      "Harper",
      "Bopolu",
      "Robertsport",
      "Buchanan",
      "Bensonville",
      "Monrovia",
      "Kakata",
      "Gbarpolu City",
      "Voinjama",
      "Paynesville",
      "Vahun",
      "Ganta",
      "Bopolu",
      "Sanniquellie",
      "Tubmanburg",
      "River Gee",
      "Gbarnga",
      "Harper",
      "Zwedru",
      "Zorzor",
      "Buchanan",
      "Bopolu",
    ],
  },
  {
    code: "mali",
    nom: "Mali",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg",
    cities: [
      "Bamako",
      "Ségou",
      "Mopti",
      "Timbuktu",
      "Kayes",
      "Sikasso",
      "Gao",
      "Koutiala",
      "Koulikoro",
      "Kati",
      "Markala",
      "Djénné",
      "Nioro du Sahel",
      "Kolokani",
      "San",
      "Kangaba",
      "Bougouni",
      "Tombouctou",
      "Goundam",
      "Bafoulabé",
      "Ségou",
      "Kati",
      "Koulikoro",
      "Kayes",
      "Kita",
      "Koutiala",
      "Sikasso",
      "Yorosso",
      "Mopti",
      "Bougouni",
      "San",
      "Markala",
      "Nioro",
      "Banamba",
      "Gao",
      "Kangaba",
      "Kolokani",
      "Kidal",
      "Tessalit",
      "Kita",
      "Ténenkou",
      "Goundam",
      "Bafoulabé",
      "Koro",
      "Bla",
      "Youwarou",
      "Ménaka",
      "Ké-Macina",
    ],
  },
  {
    code: "mauritanie",
    nom: "Mauritanie",
    devise: "MRU",
    flag: "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg",
    cities: [
      "Nouakchott",
      "Nouadhibou",
      "Kiffa",
      "Rosso",
      "Kaédi",
      "Zouérat",
      "Atar",
      "Tidjikdja",
      "Sélibaby",
      "Néma",
      "Aioun",
      "Akjoujt",
      "Aleg",
      "Bogué",
      "Guérou",
      "Boutilimit",
      "Maghama",
      "Aïoun El Atrouss",
      "Bababé",
      "Boghé",
      "Oualata",
      "Timbedra",
      "Amourj",
      "Mederdra",
      "Benne",
      "R’Kiz",
      "Bou Lanouar",
      "Louga",
      "Taboukourt",
      "Dar Naim",
      "Lemden",
      "Tachott",
      "Dawar Al Sawalih",
      "Talloul",
      "Daïra",
      "Rosso",
      "Toujounine",
      "Inal",
      "Mékhé",
      "Néma",
      "Barkéol",
      "Djiguenni",
      "Aoujeft",
      "Ouad Naga",
      "Atar",
      "Magta-Lahjar",
      "Boutilimit",
      "Hassi Cheggar",
      "Bababé",
      "Akjoujt",
      "Tékane",
      "Nouakchott",
      "Tidjikdja",
      "Selibaby",
    ],
  },
  {
    code: "niger",
    nom: "Niger",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg",
    cities: [
      "Niamey",
      "Zinder",
      "Maradi",
      "Agadez",
      "Tahoua",
      "Dosso",
      "Diffa",
      "Tillabéri",
      "Madaoua",
      "Mirriah",
      "Arlit",
      "Birni-N'Konni",
      "Gaya",
      "Dogondoutchi",
      "Tessaoua",
      "Mayahi",
      "Téra",
      "Goure",
      "Dakoro",
      "Matameye",
      "Maïné-Soroa",
      "Magaria",
      "Bouza",
      "Tanout",
      "Nguigmi",
      "Illela",
      "Keita",
      "Aguie",
      "Ayorou",
      "Tibiri",
      "Kollo",
      "Madarounfa",
      "Diffa",
      "Say",
      "Malbaza",
      "Djado",
      "Filingué",
      "Bilma",
      "Gaya",
      "Arlit",
      "Guidimouni",
    ],
  },
  {
    code: "nigeria",
    nom: "Nigeria",
    devise: "NGN",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
    cities: [
      "Lagos",
      "Kano",
      "Ibadan",
      "Kaduna",
      "Port Harcourt",
      "Benin City",
      "Maiduguri",
      "Zaria",
      "Aba",
      "Jos",
      "Ilorin",
      "Oyo",
      "Enugu",
      "Abeokuta",
      "Abuja",
      "Sokoto",
      "Onitsha",
      "Warri",
      "Okene",
      "Calabar",
      "Katsina",
      "Akure",
      "Ado-Ekiti",
      "Kumariya",
      "Bauchi",
      "Ebute Ikorodu",
      "Makurdi",
      "Minna",
      "Effon Alaiye",
      "Ilesha",
      "Owo",
      "Umuahia",
      "Ondo",
      "Damaturu",
      "Ikot Ekpene",
      "Iwo",
      "Gombe",
      "Jimeta",
      "Gusau",
      "Mubi",
      "Funtua",
      "Biu",
      "Nsukka",
      "Nguru",
      "Hadejia",
      "Ijebu Ode",
      "Ugep",
      "Ejigbo",
      "Sapele",
      "Kontagora",
      "Ife",
      "Ijero-Ekiti",
      "Wukari",
      "Wudil",
      "Lafiagi",
      "Bida",
      "Okrika",
      "Amaigbo",
      "Bama",
      "Ilobu",
      "Jalingo",
    ],
  },
  {
    code: "rdc",
    nom: "Congo Kinshasa",
    devise: "CDF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_the_Democratic_Republic_of_the_Congo.svg",
    cities: [
      "Kinshasa",
      "Lubumbashi",
      "Mbuji-Mayi",
      "Kananga",
      "Kisangani",
      "Bukavu",
      "Goma",
      "Kolwezi",
      "Likasi",
      "Tshikapa",
      "Bunia",
      "Uvira",
      "Boma",
      "Matadi",
      "Mbandaka",
      "Kikwit",
      "Mwene-Ditu",
      "Isiro",
      "Kindu",
      "Bandundu",
      "Gemena",
      "Beni",
      "Butembo",
      "Kamina",
      "Kalemie",
      "Kabinda",
      "Kipushi",
      "Kamina",
      "Kikwit",
      "Kenge",
      "Inongo",
      "Lisala",
      "Gbadolite",
      "Buta",
      "Boende",
      "Lusambo",
      "Lodja",
      "Kabalo",
      "Manono",
      "Kongolo",
      "Mweka",
      "Ilebo",
      "Kasongo",
      "Kasumbalesa",
      "Fungurume",
      "Mwene-Ditu",
      "Kamina",
      "Kambove",
      "Kaniama",
      "Kipamba",
      "Malemba-Nkulu",
      "Bukama",
      "Pweto",
      "Moba",
      "Nyunzu",
      "Kalima",
      "Kibombo",
      "Kampene",
      "Kabambare",
      "Kasaji",
      "Dilolo",
      "Sandoa",
      "Mutshatsha",
      "Kasenga",
      "Kipushi",
      "Mokambo",
      "Kasumbalesa",
      "Kasangulu",
      "Kimpese",
      "Lukala",
      "Tshela",
      "Muanda",
      "Moanda",
      "Luozi",
      "Kisantu",
      "Inkisi",
      "Mbanza-Ngungu",
      "Songololo",
      "Kasongo-Lunda",
      "Popokabaka",
      "Bulungu",
      "Idiofa",
      "Gungu",
      "Masi-Manimba",
      "Kutu",
      "Nioki",
      "Mushie",
      "Bolobo",
      "Yumbi",
      "Kiri",
      "Oshwe",
      "Bagata",
      "Mangai",
      "Kikwit",
      "Gungu",
      "Bulungu",
      "Masi-Manimba",
      "Idiofa",
      "Kenge",
      "Popokabaka",
      "Kasongo-Lunda",
      "Feshi",
      "Kahemba",
      "Gandajika",
      "Kabeya-Kamwanga",
      "Miabi",
      "Katanda",
      "Tshilenge",
      "Lupatapata",
      "Lodja",
      "Lusambo",
      "Katako-Kombe",
      "Kole",
      "Dekese",
      "Dibaya",
      "Demba",
      "Kazumba",
      "Dimbelenge",
      "Luiza",
      "Luebo",
      "Mweka",
      "Tshikapa",
      "Ilebo",
      "Kamonia",
      "Sandoa",
      "Mutshatsha",
      "Kasaji",
      "Dilolo",
      "Kapanga",
      "Manono",
      "Kongolo",
      "Kabalo",
      "Nyunzu",
      "Kalemie",
      "Moba",
      "Pweto",
      "Bukama",
      "Malemba-Nkulu",
      "Kaniama",
      "Kipamba",
      "Kambove",
      "Likasi",
      "Lubumbashi",
      "Kasenga",
      "Kipushi",
      "Mokambo",
      "Kasumbalesa",
      "Fungurume",
      "Kolwezi",
      "Mutshatsha",
      "Sandoa",
      "Kasaji",
      "Dilolo",
      "Kapanga",
      "Mwene-Ditu",
      "Kabinda",
      "Lodja",
      "Lusambo",
      "Katako-Kombe",
      "Kole",
      "Boende",
      "Befale",
      "Bokungu",
      "Monkoto",
      "Ikela",
      "Djolu",
      "Basankusu",
      "Bolomba",
      "Makanza",
      "Bikoro",
      "Ingende",
      "Lukolela",
      "Mbandaka",
      "Lisala",
      "Bumba",
      "Bongandanga",
      "Budjala",
      "Gemena",
      "Libenge",
      "Zongo",
      "Mobayi-Mbongo",
      "Bosobolo",
      "Businga",
      "Yakoma",
      "Buta",
      "Aketi",
      "Bondo",
      "Ango",
      "Bambesa",
      "Poko",
      "Isiro",
      "Wamba",
      "Rungu",
      "Niangara",
      "Dungu",
      "Faradje",
      "Watsa",
      "Watsa",
      "Aru",
      "Ariwara",
      "Bunia",
      "Mahagi",
      "Djugu",
      "Mambasa",
      "Komanda",
      "Bafwasende",
      "Banalia",
      "Yahuma",
      "Opala",
      "Ubundu",
      "Kisangani",
      "Isangi",
      "Basoko",
      "Yahuma",
      "Ubundu",
      "Opala",
      "Bafwasende",
      "Banalia",
      "Mambasa",
      "Komanda",
      "Djugu",
      "Mahagi",
      "Ariwara",
      "Aru",
    ],
  },
  {
    code: "senegal",
    nom: "Sénégal",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg",
    cities: [
      "Dakar",
      "Thiès",
      "Grand Dakar",
      "Ziguinchor",
      "Touba",
      "Rufisque",
      "Kaolack",
      "Mbour",
      "Saint-Louis",
      "Diourbel",
      "Louga",
      "Fatick",
      "Kolda",
      "Tambacounda",
      "Médina",
      "Dakar Plateau",
      "Sédhiou",
      "Joal-Fadiouth",
      "Mbake",
      "Podor",
      "Pikine",
      "Tivaouane",
      "Kédougou",
      "Vélingara",
      "Kayar",
      "Kébémer",
      "Nioro du Rip",
      "Pourham",
      "Guédiawaye",
      "Médina Gounass",
      "Koungheul",
      "Darou Mousty",
      "Sokone",
      "Ourossogui",
      "Pout",
      "Ngaye Méckhe",
      "Kaolack",
      "Diourbel",
      "Tambacounda",
      "Mbacké",
      "Kaffrine",
      "Dagana",
      "Kolda",
      "Saint-Louis",
      "Ziguinchor",
      "Louga",
      "Touba",
      "Rufisque",
      "Thiès",
      "Mbour",
      "Dakar",
    ],
  },
  {
    code: "sierra_leone",
    nom: "Sierra Leone",
    devise: "SLL",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg",
    cities: [
      "Freetown",
      "Bo",
      "Kenema",
      "Koidu",
      "Makeni",
      "Lunsar",
      "Port Loko",
      "Kabala",
      "Pujehun",
      "Kailahun",
      "Magburaka",
      "Bonthe",
      "Masiaka",
      "Port Loko",
      "Kambia",
      "Pujehun",
      "Marampa",
      "Waterloo",
      "Kamakwie",
      "Koribondo",
      "Lungi",
      "Karene",
      "Yengema",
      "Rokupr",
      "Goderich",
      "Lunsar",
      "Magburaka",
      "Rokel",
      "Gberia Fotombu",
      "Baoma",
      "Yonibana",
      "Lunga",
      "Goderich",
      "Shenge",
      "Kailahun",
      "Kenema",
      "Zimmi",
      "Pandebu-Tokpombu",
      "Sumbuya",
      "Makeni",
      "Kabala",
      "Bumpe",
      "Baiima",
      "Bo",
      "Falaba",
      "Matru",
      "Kambia",
      "Segbwema",
      "Yele",
      "Kawama",
      "Zimmi",
      "Masimera",
      "Tongo",
      "Pendembu",
      "Kambia",
      "Pandebu-Tokpombu",
      "Rokupr",
      "Bonthe",
      "Potoru",
      "Kailahun",
      "Pendembu",
      "Mattru",
      "Kenema",
      "Segbwema",
      "Baiima",
      "Falaba",
      "Gberia Fotombu",
    ],
  },
  {
    code: "togo",
    nom: "Togo",
    devise: "XOF",
    flag: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_Togo_%283-2%29.svg",
    cities: [
      "Lomé",
      "Sokodé",
      "Kara",
      "Atakpamé",
      "Palimé",
      "Bassar",
      "Tsevie",
      "Aného",
      "Sansanné-Mango",
      "Dapaong",
      "Tchamba",
      "Niamtougou",
      "Bafilo",
      "Sotouboua",
      "Vogan",
      "Badou",
      "Amlamé",
      "Kandé",
      "Notsé",
      "Tchaoudjo",
      "Notse",
      "Tabligbo",
      "Vogan",
      "Bassar",
      "Dapaong",
      "Atakpamé",
      "Niamtougou",
      "Kara",
      "Lomé",
      "Kpalimé",
      "Tsevie",
      "Sokodé",
      "Badou",
      "Amlamé",
      "Tchamba",
      "Aného",
      "Sotouboua",
      "Sansanné-Mango",
      "Bafilo",
      "Notsé",
      "Tandjouaré",
      "Vogan",
      "Kandé",
      "Mango",
      "Kpagouda",
      "Bassar",
      "Tchaoudjo",
    ],
  },
  {
    code: "tunisie",
    nom: "Tunisie",
    devise: "TND",
    flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg",
    cities: [
      "Tunis",
      "Sfax",
      "Sousse",
      "Midoun",
      "Kairouan",
      "Bizerte",
      "Gabès",
      "Aryanah",
      "Gafsa",
      "El Mourouj",
      "Tunis",
      "Kasserine",
      "Sousse",
      "Monastir",
      "Nabeul",
      "Sfax",
      "Tataouine",
      "Béja",
      "La Goulette",
      "Gafsa",
      "El Mourouj",
      "Kairouan",
      "Sidi Bouzid",
      "Gabès",
      "Bizerte",
      "Aryanah",
      "Ben Arous",
      "Kram",
      "La Marsa",
      "La Manouba",
      "Hammam Sousse",
      "Mahdia",
      "Sidi Hassine",
      "Jendouba",
      "Zarzis",
      "Sousse",
      "Grombalia",
      "Gabès",
      "Sfax",
      "Tataouine",
      "Kasserine",
      "Moknine",
      "Hammam Lif",
      "Douane",
      "Monastir",
      "Tunis",
      "Nabeul",
      "Bizerte",
      "Kairouan",
      "Gafsa",
      "Ben Arous",
    ],
  },
  {
    code: "zambie",
    nom: "Zambie",
    devise: "ZMW",
    flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg",
    cities: [
      "Lusaka",
      "Kitwe",
      "Ndola",
      "Kabwe",
      "Chingola",
      "Mufulira",
      "Luanshya",
      "Livingstone",
      "Kasama",
      "Chipata",
      "Kalulushi",
      "Mazabuka",
      "Chililabombwe",
      "Mongu",
      "Kafue",
      "Ndola",
      "Kasama",
      "Chambishi",
      "Luanshya",
      "Mufulira",
      "Mpika",
      "Nchelenge",
      "Kapiri Mposhi",
      "Kalomo",
      "Kansanshi",
      "Chinsali",
      "Mansa",
      "Kawambwa",
      "Mbala",
      "Petauke",
      "Samfya",
      "Choma",
      "Monze",
      "Solwezi",
      "Chirundu",
      "Kaputa",
      "Kaoma",
      "Mwinilunga",
      "Luwingu",
      "Serenje",
      "Nakonde",
      "Sesheke",
      "Mumbwa",
      "Isoka",
      "Mkushi",
      "Maamba",
      "Lundazi",
      "Namwala",
    ],
  },
  {
    code: "zimbabwe",
    nom: "Zimbabwe",
    devise: "ZWL",
    flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg",
    cities: [
      "Harare",
      "Bulawayo",
      "Chitungwiza",
      "Mutare",
      "Gweru",
      "Epworth",
      "Kwekwe",
      "Kadoma",
      "Masvingo",
      "Chinhoyi",
      "Marondera",
      "Norton",
      "Chegutu",
      "Bindura",
      "Zvishavane",
      "Victoria Falls",
      "Hwange",
      "Redcliff",
      "Ruwa",
      "Beitbridge",
      "Chiredzi",
      "Gokwe",
      "Shurugwi",
      "Gwanda",
      "Shamva",
      "Chivhu",
      "Mazowe",
      "Zvishavane",
      "Mashava",
      "Banket",
      "Mutoko",
      "Murewa",
      "Glendale",
      "Greendale",
      "Mbare",
      "Mufakose",
      "Budiriro",
      "Dzivarasekwa",
      "Kuwadzana",
      "Glen View",
      "Highfields",
      "Warren Park",
      "Waterfalls",
      "Mount Pleasant",
      "Avondale",
      "Borrowdale",
      "Marlborough",
      "Ruwa",
    ],
  },
];

exports.TYPE_RETOUR_PRDUITS = [
  {
    type: "full",
    nom: "remboursement total",
  },
  {
    type: "half",
    nom: "remboursement partiel",
  },
  {
    type: "tip",
    nom: "avoir",
  },
];

exports.MONTHS = [
  { code: 1, nom: "Janvier" },
  { code: 2, nom: "Février" },
  { code: 3, nom: "Mars" },
  { code: 4, nom: "Avril" },
  { code: 5, nom: "Mai" },
  { code: 6, nom: "Juin" },
  { code: 7, nom: "Juillet" },
  { code: 8, nom: "Août" },
  { code: 9, nom: "Septembre" },
  { code: 10, nom: "Octobre" },
  { code: 11, nom: "Novembre" },
  { code: 12, nom: "Décembre" },
];

exports.MARQUES = [
  { code: 1, nom: "Solibra" },
  { code: 2, nom: "Brassivoire" },
  { code: 3, nom: "Brakina" },
  { code: 4, nom: "Bramali" },
  { code: 5, nom: "BGI" },
  { code: 6, nom: "Coca-Cola" },
];

exports.START_TIP_DAY = new Date("2023-10-08T00:00:00.000Z");
